=== axAilotl/thoth/spec/ccf/0.1.2-rc1/schemas/objects/commit-member.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:ccf:schema:0.1.2-rc1:objects.commit-member",
  "title": "CCF Commit Member",
  "type": "object",
  "properties": {
    "commit_sequence": {
      "$ref": "urn:ccf:schema:0.1.2-rc1:common.defs#/$defs/uint64"
    },
    "commit_position": {
      "type": "integer",
      "minimum": 0,
      "maximum": 2147483647
    },
    "admitted_at": {
      "$ref": "urn:ccf:schema:0.1.2-rc1:common.defs#/$defs/timestamp"
    },
    "object_kind": {
      "enum": [
        "record",
        "link",
        "blob"
      ]
    },
    "object_id": {
      "$ref": "urn:ccf:schema:0.1.2-rc1:common.defs#/$defs/objectUrn"
    },
    "object_hash": {
      "$ref": "urn:ccf:schema:0.1.2-rc1:common.defs#/$defs/digest"
    }
  },
  "required": [
    "commit_sequence",
    "commit_position",
    "admitted_at",
    "object_kind",
    "object_id",
    "object_hash"
  ],
  "additionalProperties": false
}

=== axAilotl/thoth/spec/ccf/0.1.2-rc1/examples/thoth-capture/commit-members-2.json
[
  {
    "commit_sequence": "2",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:3e98b052-de3c-4c51-b6a0-e5eee3935196",
    "object_hash": "sha256:c8499f4f31b77e8f3ba413a0d1b873ad9dbf61dfeba0d1dec49e130761a93e02"
  },
  {
    "commit_sequence": "2",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:7a2cc59c-52e4-41cb-8e95-820bc655ee8d",
    "object_hash": "sha256:eac9e95f6878a0a4e549a4d0aec13485ed09ce69c54ddb691581742596dc7b7c"
  },
  {
    "commit_sequence": "2",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:e10694f9-8903-413a-9b53-9fb5765169ad",
    "object_hash": "sha256:240cf09bd5f66baf67358b3875699b8b6fe54bf5368cac89464882a3512bba28"
  },
  {
    "commit_sequence": "2",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:1e319572-9fca-4ab5-9f9a-1e73eddb3a8f",
    "object_hash": "sha256:76814769fd69a39e6d598754775dddf5bda0385daf7a29362f56047f1bbf6f7d"
  },
  {
    "commit_sequence": "2",
    "commit_position": 4,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:2e9ea5e1-77c8-4d7e-9bf4-c411f8ace535",
    "object_hash": "sha256:20a065449324b09ca6c0f500b0d405a9ebd63e17b8e69a3eba2ab8a5d4bc19f6"
  },
  {
    "commit_sequence": "2",
    "commit_position": 5,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:22ca77c3-ad70-4d53-84eb-97c80a2780e5",
    "object_hash": "sha256:6ca896f147e69757891dd68588f03158ff2dbdb6a19141865ce49f037ea8d7ec"
  },
  {
    "commit_sequence": "2",
    "commit_position": 6,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:1428cd68-e7eb-4022-bb2b-a2d9695c626e",
    "object_hash": "sha256:69b7f83b1ad392e4ef7a367aa0278745cfd278a993fdc4cb41e9968697ec9a42"
  },
  {
    "commit_sequence": "2",
    "commit_position": 7,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:9a1f6b0d-9725-4e48-bbf4-7c614e10f454",
    "object_hash": "sha256:e75d420cfe4b01a59e658ed38a66c5099d831cc350a670b4151288bb61005df2"
  },
  {
    "commit_sequence": "2",
    "commit_position": 8,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:cf2e5dfe-a30d-457a-b924-b22f4df4e40b",
    "object_hash": "sha256:d833066f9b021434f08eb1b00e7c20b8d4d3f647ef26ab02599a41ffeee14fc5"
  },
  {
    "commit_sequence": "2",
    "commit_position": 9,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:375828bd-15b4-4610-956b-86088c737a11",
    "object_hash": "sha256:24510d4a32ddc5d3ee0bcaf844c61a79adcdf977a92343b0c0191c868e03ad9d"
  },
  {
    "commit_sequence": "2",
    "commit_position": 10,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:16f4474b-ecea-44de-9cd0-59b4a1523e10",
    "object_hash": "sha256:8d45babb1dff854b8ed6c75fbc1dfd4a5f611121b957cb3ffe1e5ac72e88e1ad"
  },
  {
    "commit_sequence": "2",
    "commit_position": 11,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:ba3fe509-e43d-4879-a298-d3a7d66e01cf",
    "object_hash": "sha256:77d114b1ee49a8140568d7e2da0920bb90056e9c72e9ab564d847b1404dd595b"
  },
  {
    "commit_sequence": "2",
    "commit_position": 12,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:e41b724b-c3e8-4550-880f-ac16f0b07399",
    "object_hash": "sha256:1902fc2af27f984641c9c4525cf3e783c3eb77090a184c6a4a90988abcdf68a9"
  },
  {
    "commit_sequence": "2",
    "commit_position": 13,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:82de4b0d-a83d-4db8-8bf0-522f87b8b818",
    "object_hash": "sha256:5899b365af0f883808bf8568e7cab07d3ba488cbc592fec7e42c177d6950435f"
  },
  {
    "commit_sequence": "2",
    "commit_position": 14,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:2ce385ef-a58d-405b-9dcd-04703d0f60f4",
    "object_hash": "sha256:2b76bb2d7009df60d3898c27604a617bf3e71197898c227aee85f85285641e9c"
  },
  {
    "commit_sequence": "2",
    "commit_position": 15,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:caaba9bd-5b2a-47fd-90f7-85a449eea291",
    "object_hash": "sha256:8ba9c9f49efd09e35f421732901816898f5d9ac07e3d155aa2efef5abc68bd22"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.1/examples/thoth-capture/commit-members-2.json
[
  {
    "commit_sequence": "2",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:8a28d4f2-8e94-4ab1-a0b4-08d6c6f1cc81",
    "object_hash": "sha256:806f07206e55fbba189a91157530f76349322eb956cd9558a67d85f74fee68c4"
  },
  {
    "commit_sequence": "2",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:86fb5ba3-070c-4557-b5f5-24688206ad80",
    "object_hash": "sha256:f0cd7337fdd637fdb4d8c14f6231f4a479255059bb932b1613bb90f8275ccc7a"
  },
  {
    "commit_sequence": "2",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:ec80197e-7b6d-4164-a82a-317f7ef748e8",
    "object_hash": "sha256:361938dba19d320ed875f3d67e2580cbc410a2691c5a0c66946977bed1b53466"
  },
  {
    "commit_sequence": "2",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:11ecb434-503d-475e-8d94-602398794896",
    "object_hash": "sha256:3259adc2f62e243d4bbbe1fbcd501f2fdb5bc97c1ec0aa916e0aa8ba807cd6c3"
  },
  {
    "commit_sequence": "2",
    "commit_position": 4,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:d0d98ab3-0493-4491-bde9-ccfb70e6c82d",
    "object_hash": "sha256:e5ec89852793b0a4571aa99efd9d26984d3147023a29b340b581e34275fdaf2b"
  },
  {
    "commit_sequence": "2",
    "commit_position": 5,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:2fd2e84a-3d89-47b6-83c2-1be7729ff839",
    "object_hash": "sha256:d885524632af1090925e28e0b6f668feb91582182ebcf830e9e967d38a8fad7f"
  },
  {
    "commit_sequence": "2",
    "commit_position": 6,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:6acc6514-2dab-4ba0-9851-89d51a83e1c1",
    "object_hash": "sha256:43834ad15c3ee9ff9f06236ce23d723217f849ec29d6f84b7a83d5d4fdc4fa00"
  },
  {
    "commit_sequence": "2",
    "commit_position": 7,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:85441aca-60e4-4a94-bf4b-10e71046dbec",
    "object_hash": "sha256:acd03f5b69860e183955ec0a1c051c4be7ed47498f47c6adf6c4222c861487ee"
  },
  {
    "commit_sequence": "2",
    "commit_position": 8,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:b8eca641-3df7-4f0f-90c4-5ad0b1c4bed2",
    "object_hash": "sha256:9c594678aa461bc09d26aafdfeab7465e8253de62c63f42dd14e6239cbc1d834"
  },
  {
    "commit_sequence": "2",
    "commit_position": 9,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:280e2137-89fe-4da4-aa7f-2e132c0e51b6",
    "object_hash": "sha256:ab54c6188ed8375a257d7f16328b690500c644ce167fe228055b79ab444b7de8"
  },
  {
    "commit_sequence": "2",
    "commit_position": 10,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:3b8624df-05b0-4bb0-9a4a-092a183f50a9",
    "object_hash": "sha256:9ecd48a8b27a7489ce74fb3414a80d0a500a2a5807c3c2c504bb4127a71438e9"
  },
  {
    "commit_sequence": "2",
    "commit_position": 11,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:b6f86d6f-d5ae-42e1-9b45-1e196b3bc15a",
    "object_hash": "sha256:ee41dafe51682c78554f0832eb9c51213e1f56fda60382cc265d893d2d7b13a8"
  },
  {
    "commit_sequence": "2",
    "commit_position": 12,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:a4357ced-f874-4ab8-97ad-6eb95171879d",
    "object_hash": "sha256:ea87fe4f15cf0345d3ac5aed6b5460b04ac7f4108f4aa7d1d8378ac2d29cba17"
  },
  {
    "commit_sequence": "2",
    "commit_position": 13,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:39d32f3d-12e0-4c8a-8014-5325d3c835e3",
    "object_hash": "sha256:44a84f20723ce77ea3b697a6a5ee6b5e79aea2de2f97499764b2d9807d9f2be9"
  },
  {
    "commit_sequence": "2",
    "commit_position": 14,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:394dbb9d-d4d3-4796-b5fe-473c2004f761",
    "object_hash": "sha256:f889d96d2e07a649d02a55bfef6e4766c9557a7a42d1924bba8086c0d8a5eb50"
  },
  {
    "commit_sequence": "2",
    "commit_position": 15,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:1347aae2-aa68-44ff-bb95-fd864a648d0f",
    "object_hash": "sha256:8767e649bd680de697a52de5e21ae5b7e4856b14423c2787f7432700da1d480a"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.2/examples/personal-archive/commit-members-2.json
[
  {
    "commit_sequence": "2",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4e9f8cc9-563a-4d61-8221-9f55e9db39bd",
    "object_hash": "sha256:058b11e05d47c0ead576693f79ae9b5884700c3fb2cd3a253acf813d58e3ac43"
  },
  {
    "commit_sequence": "2",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:b7972dfb-99c3-4376-897f-3c9f2848138b",
    "object_hash": "sha256:cf8a4ca385af4481e4d85fd445b2ed31154c7ba427051761abde1dbb962c6dfd"
  },
  {
    "commit_sequence": "2",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4d8feff5-3956-4190-9679-203f34a09de1",
    "object_hash": "sha256:57b2c937503a76f495dd1fcef4541149739e054f9d148cd59a9dd015ddb51e1c"
  },
  {
    "commit_sequence": "2",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4bc9c0eb-a3b3-4d1f-8b61-d58225d3a203",
    "object_hash": "sha256:3184970b804382da516734038ebb7123892f2b5a72dbd4546ebc3ec8af983f0f"
  },
  {
    "commit_sequence": "2",
    "commit_position": 4,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:63607ea0-9d26-4625-ab23-65ce7415b571",
    "object_hash": "sha256:32b9c32f66753625bb93c958c2e985f207b884eb01ffdf52b702dddccec5f61e"
  },
  {
    "commit_sequence": "2",
    "commit_position": 5,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:396faaaf-52c3-494d-b456-bbb1b8889cbf",
    "object_hash": "sha256:86063f0c3be7354e25180ab69146c799ba0014e2f6c185a5f8c9867dd919eec8"
  },
  {
    "commit_sequence": "2",
    "commit_position": 6,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:a01f8c5c-8278-4a2b-bccb-c270ca803586",
    "object_hash": "sha256:947c6119cba968cbde452417a084c971ef4fcfc38b8a53758d834fc40919bb91"
  },
  {
    "commit_sequence": "2",
    "commit_position": 7,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:2e96f116-6c1a-4216-8ac5-63d0b5da108f",
    "object_hash": "sha256:7bb840239d50a09a5ad157a2b5b6e11f4e15a829608574a03a90212b692d8ccc"
  },
  {
    "commit_sequence": "2",
    "commit_position": 8,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:ce293b52-58f1-4f52-87d1-4b7d5e75edb8",
    "object_hash": "sha256:6b06c698dadc1f8a8041708fdfd7768d518c2dea5302b851fa877d4ecd2beb3e"
  },
  {
    "commit_sequence": "2",
    "commit_position": 9,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4034e10b-7a56-46b6-9162-d1cf909f8a78",
    "object_hash": "sha256:a27603dec50495e497f1c2aeb41ba06a930091abf25bdaf9a98ca1f377c33cc6"
  },
  {
    "commit_sequence": "2",
    "commit_position": 10,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:649042b4-1519-4dfb-8de9-9dffb167de34",
    "object_hash": "sha256:588c3252f8265098eeadef78427b3d6259b3f9b3f3d6ebb07831931f186d2b6e"
  },
  {
    "commit_sequence": "2",
    "commit_position": 11,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:a3a6c051-271d-47cf-bee5-35fc66d903c2",
    "object_hash": "sha256:b557d79fb6456c645ee63e272e6c40759453c14e09689305a94b6c07bf5fc826"
  },
  {
    "commit_sequence": "2",
    "commit_position": 12,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:1ae193bd-79bd-4535-bbd3-a670dba025ff",
    "object_hash": "sha256:e8f2483f6afa75903ec6eba4fb20d2f2082522674d797584dd3d78f145b45004"
  },
  {
    "commit_sequence": "2",
    "commit_position": 13,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:098c30cb-13fa-42b1-96f4-923ce82dd9d3",
    "object_hash": "sha256:108987c29bd07c5713b35b151a22063c97e7e0a484c3cdfd6178ac4d4d63ba05"
  },
  {
    "commit_sequence": "2",
    "commit_position": 14,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:d8302220-fcda-466a-ae4f-58b116746b4e",
    "object_hash": "sha256:d41c0ce4c27dbd1f1a5fece4a7ea11ad501b981f199e878ade760ae592d41384"
  },
  {
    "commit_sequence": "2",
    "commit_position": 15,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:a3eedfcb-016b-4f1b-a58a-3afe9b9d1e62",
    "object_hash": "sha256:3e13d7263907e69d010adb51ee5628e66638461ceaf18b3bc57422bdb36f85a1"
  },
  {
    "commit_sequence": "2",
    "commit_position": 16,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:76a63205-f0d1-4502-b29e-c44e0d1c6645",
    "object_hash": "sha256:845b1c1e3ad8d6de5d11eb46bb0ac2cc6f9e3a19fda7a6caaab04ed5140bd512"
  },
  {
    "commit_sequence": "2",
    "commit_position": 17,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:e807d6c8-6589-4ac2-bed4-032207901261",
    "object_hash": "sha256:0d556f707d177820a141ab619123e133e8007c584b797a8f646e2a044eaa24e7"
  },
  {
    "commit_sequence": "2",
    "commit_position": 18,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:c78ac8a7-56fa-4c79-b74b-640d3cc82a09",
    "object_hash": "sha256:31c2d69109470440b4cf38516f6b3aee3505163ea03013472596aa8ff5145cca"
  },
  {
    "commit_sequence": "2",
    "commit_position": 19,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:4393e9d0-c150-448d-9b27-05872973abab",
    "object_hash": "sha256:eaca7887bf6f73ab096609661ec726bfb3c67812e7ddcba62448a0e8088a0c8d"
  },
  {
    "commit_sequence": "2",
    "commit_position": 20,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:ce293b52-58f1-4f52-87d1-4b7d5e75edb8",
    "object_hash": "sha256:d84400c41db8123f26456c85e10f50e56bd374d46834d871e7aee74586d96536"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.2/examples/thoth-capture/commit-members-2.json
[
  {
    "commit_sequence": "2",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4e9f8cc9-563a-4d61-8221-9f55e9db39bd",
    "object_hash": "sha256:6b666c6508b1e015caff5ef0e0899fee2b73344bb0611df013fbc4891890fa09"
  },
  {
    "commit_sequence": "2",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:b7972dfb-99c3-4376-897f-3c9f2848138b",
    "object_hash": "sha256:97b5eea3f6178a34a6c0633eb31b15eca8cf22419fdb0e584cff710dd43af303"
  },
  {
    "commit_sequence": "2",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4d8feff5-3956-4190-9679-203f34a09de1",
    "object_hash": "sha256:ab6c98e35bb7aba8b9c7aa067c387700157562fef539b79533851c1533997d86"
  },
  {
    "commit_sequence": "2",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4bc9c0eb-a3b3-4d1f-8b61-d58225d3a203",
    "object_hash": "sha256:3fc5342f78e8c6d481bbef32ed03caf996b3681c632b9489976baa51706dea60"
  },
  {
    "commit_sequence": "2",
    "commit_position": 4,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:63607ea0-9d26-4625-ab23-65ce7415b571",
    "object_hash": "sha256:b6019ece8627cb30a56769cffdc126850a00532bcf504e80c4d88a5dfbddf9e9"
  },
  {
    "commit_sequence": "2",
    "commit_position": 5,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:396faaaf-52c3-494d-b456-bbb1b8889cbf",
    "object_hash": "sha256:be0e7176a89e4ac53547a5e50076ee56f0a5b1a1bbf3a4cc108db9312034bdcb"
  },
  {
    "commit_sequence": "2",
    "commit_position": 6,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:a01f8c5c-8278-4a2b-bccb-c270ca803586",
    "object_hash": "sha256:b0d847c5bc0cf589dd8587b5e471010ab7611227048d28016385cb5abe90731b"
  },
  {
    "commit_sequence": "2",
    "commit_position": 7,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:2e96f116-6c1a-4216-8ac5-63d0b5da108f",
    "object_hash": "sha256:de9a7f96a8ab67b000d9c1214130f9a9f18cbf3322bb9a98dfeaf7d22770aced"
  },
  {
    "commit_sequence": "2",
    "commit_position": 8,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:ce293b52-58f1-4f52-87d1-4b7d5e75edb8",
    "object_hash": "sha256:bd40aacd05e9fdd7f208d483c564c4c32c3a887ee402dfa1c89386fa8efcb69b"
  },
  {
    "commit_sequence": "2",
    "commit_position": 9,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:4034e10b-7a56-46b6-9162-d1cf909f8a78",
    "object_hash": "sha256:3a3cec80d39ce2f26ef84b1ca971a46b23e3fba002a36083ace3b31cc2ec12b3"
  },
  {
    "commit_sequence": "2",
    "commit_position": 10,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:649042b4-1519-4dfb-8de9-9dffb167de34",
    "object_hash": "sha256:588c3252f8265098eeadef78427b3d6259b3f9b3f3d6ebb07831931f186d2b6e"
  },
  {
    "commit_sequence": "2",
    "commit_position": 11,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:a3a6c051-271d-47cf-bee5-35fc66d903c2",
    "object_hash": "sha256:cc7e967a55ac68a3e39539bf6dbae9e3ba7dec50c4768d7eb878382b525bbb7f"
  },
  {
    "commit_sequence": "2",
    "commit_position": 12,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:1ae193bd-79bd-4535-bbd3-a670dba025ff",
    "object_hash": "sha256:0c79cc9677f08979c81d13513a4a13483eae97c2141b8b9064367069254fe2ad"
  },
  {
    "commit_sequence": "2",
    "commit_position": 13,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:098c30cb-13fa-42b1-96f4-923ce82dd9d3",
    "object_hash": "sha256:c177591b051e621daff18c9b8f0238d23f6c3d6d7f0d93cce0c859bb4eb40ef7"
  },
  {
    "commit_sequence": "2",
    "commit_position": 14,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:d8302220-fcda-466a-ae4f-58b116746b4e",
    "object_hash": "sha256:85f9ed72cae4dc91f8c50dfd39ee3d2fcab0ed85307c7883b01d0c1c32e343b5"
  },
  {
    "commit_sequence": "2",
    "commit_position": 15,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:a3eedfcb-016b-4f1b-a58a-3afe9b9d1e62",
    "object_hash": "sha256:5f939c7cd2bc77fa47e7fda7ef8868b12681a55976d2ed1e6175de5afe697e20"
  },
  {
    "commit_sequence": "2",
    "commit_position": 16,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:76a63205-f0d1-4502-b29e-c44e0d1c6645",
    "object_hash": "sha256:67ec2580607a7cf9d2e128889ba90ccabcbaa58edabe0ec5a6202b05ad8b52fb"
  },
  {
    "commit_sequence": "2",
    "commit_position": 17,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:e807d6c8-6589-4ac2-bed4-032207901261",
    "object_hash": "sha256:ebb9e65a55d66e8a428c71f18da6999ce9e75d0b2354179ce10839a4992e54ac"
  },
  {
    "commit_sequence": "2",
    "commit_position": 18,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "link",
    "object_id": "urn:ccf:link:c78ac8a7-56fa-4c79-b74b-640d3cc82a09",
    "object_hash": "sha256:110af19be7f59fe2113ac0f65983f1b003e8d3ecf993a39a6dcd03b28fbe4beb"
  },
  {
    "commit_sequence": "2",
    "commit_position": 19,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:4393e9d0-c150-448d-9b27-05872973abab",
    "object_hash": "sha256:f527192180ee4a4764d4b4a9cf3037197f0a6936c21e3210eb1d59263110379a"
  },
  {
    "commit_sequence": "2",
    "commit_position": 20,
    "admitted_at": "2026-08-11T21:42:21.000Z",
    "object_kind": "blob",
    "object_id": "urn:ccf:blob:ce293b52-58f1-4f52-87d1-4b7d5e75edb8",
    "object_hash": "sha256:fb663fead2cd851b2088f13d489147fabc193694d0735727731aca88af0eba71"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.2-rc1/examples/thoth-capture/commit-members-1.json
[
  {
    "commit_sequence": "1",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:b1d37833-91d1-4bfd-8f90-b949a0a85df6",
    "object_hash": "sha256:ea7ff72d1b9ad13aee43307b373a0ad3c893e4d9f54f3f6a8562d8c9f66e29ad"
  },
  {
    "commit_sequence": "1",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:8f1d4498-c2e8-4457-a998-5c8c5a43c57b",
    "object_hash": "sha256:d9a9ce45b1bc82a508cfcd82ffe99c398d3ea195695dcc4d0d28054b226aeb78"
  },
  {
    "commit_sequence": "1",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:8006f1b0-5c0a-4209-890a-e86f44ef189a",
    "object_hash": "sha256:cb563941a245f1b0a91c1dbaecd7768db0ea9d5c6f30dbf8ea6560db970cd9e3"
  },
  {
    "commit_sequence": "1",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:5744816a-35ff-47ff-a452-e177a4b839c9",
    "object_hash": "sha256:7d4b063402f031922b2c268ca47b2c3dc3dd96ee03bddea25b02eb0745de6693"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.1/examples/thoth-capture/commit-members-1.json
[
  {
    "commit_sequence": "1",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:15b2492f-59a8-4e6a-93a2-c3b4a134c345",
    "object_hash": "sha256:58efe94b07ee215fee6bd8a26d5a8c19801658e3b3011a0d643d248a7087e564"
  },
  {
    "commit_sequence": "1",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:ef73705f-4910-4bfa-ab60-cf08d8169b6d",
    "object_hash": "sha256:753e35433076afd41afab1f992d97b00f284093be0421cca3420cbf9802ad107"
  },
  {
    "commit_sequence": "1",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:a5e2e478-195c-4f2e-8329-a13a1e1fef7e",
    "object_hash": "sha256:76a1dadc2a87641bb10b9f11c775bf7a4f6deb8960866ab15db73dc0d70ead39"
  },
  {
    "commit_sequence": "1",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:fa001749-4cb0-4117-a8b7-9dbc02a811cd",
    "object_hash": "sha256:2ef0598fffc14d3edfb0429f0f2efbccae3d8d79b21b33dbb6fbf25561867c62"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.2/examples/personal-archive/commit-members-1.json
[
  {
    "commit_sequence": "1",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:03e09d92-b68b-467d-b3c9-18a15be891be",
    "object_hash": "sha256:6291e538838914ffe6991504bc00ca896c4eb53af3cc6e6ee4e3effdaeb3f03b"
  },
  {
    "commit_sequence": "1",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:908e42a4-f136-458f-8cf9-7597922fab21",
    "object_hash": "sha256:ff44511c5cb03f3ff1129d5448446dd1bd46ee05d488a3c2acc43839082d16c9"
  },
  {
    "commit_sequence": "1",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:682d6151-5dd6-42d8-874c-895c3a501f09",
    "object_hash": "sha256:53fefce825e44eb31c411be72932eb3278a4765ae48aaeef3f991bfc6aca654f"
  },
  {
    "commit_sequence": "1",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:405c475b-1c4c-4e05-b978-28246bb3a5fa",
    "object_hash": "sha256:7f08f57e56c0a776ea1b10abe2260d7500b0c382c831a08f633cf0166b4e6f1d"
  }
]

=== axAilotl/thoth/spec/ccf/0.1.2/examples/thoth-capture/commit-members-1.json
[
  {
    "commit_sequence": "1",
    "commit_position": 0,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:03e09d92-b68b-467d-b3c9-18a15be891be",
    "object_hash": "sha256:e57851ddec5a839632de3ebd13c350ae8db724496473078180d94f5f52fcf225"
  },
  {
    "commit_sequence": "1",
    "commit_position": 1,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:908e42a4-f136-458f-8cf9-7597922fab21",
    "object_hash": "sha256:74b9093df187b9d10c742f3bae34bbde6046c5cef42f4d7e25213a26c9b717aa"
  },
  {
    "commit_sequence": "1",
    "commit_position": 2,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:682d6151-5dd6-42d8-874c-895c3a501f09",
    "object_hash": "sha256:9e00cefbab5cefcea109e27788d83f4e14881e3b161475aba1653bd2dd377827"
  },
  {
    "commit_sequence": "1",
    "commit_position": 3,
    "admitted_at": "2026-08-11T21:40:01.000Z",
    "object_kind": "record",
    "object_id": "urn:ccf:record:405c475b-1c4c-4e05-b978-28246bb3a5fa",
    "object_hash": "sha256:7f08f57e56c0a776ea1b10abe2260d7500b0c382c831a08f633cf0166b4e6f1d"
  }
]
